create table url_url_stats (url_id int8 not null, url_stats_id int8 not null, primary key (url_id, url_stats_id));
create table url_stats (id  bigserial not null, created_at timestamp, deleted_at timestamp, updated_at timestamp, url_id int8 not null, primary key (id));
alter table url_url_stats add constraint UK_l8de4ny4bkblamhklm7c5nhcv unique (url_stats_id);
alter table url_url_stats add constraint FKixdoppap48w5qd62i2x9oqsq foreign key (url_stats_id) references url_stats;
alter table url_url_stats add constraint FK97wbkty0yufg3cyfenc3q1w0 foreign key (url_id) references url;
alter table url_stats add constraint FKqq0uktlox72vmsl5q67c305mf foreign key (url_id) references url;
create table url (id  bigserial not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
create table url_url_stats (url_id int8 not null, url_stats_id int8 not null, primary key (url_id, url_stats_id));
create table url_stats (id  bigserial not null, created_at timestamp, deleted_at timestamp, device_type varchar(255), updated_at timestamp, url_id int8 not null, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
alter table url_url_stats add constraint UK_l8de4ny4bkblamhklm7c5nhcv unique (url_stats_id);
alter table url_url_stats add constraint FKixdoppap48w5qd62i2x9oqsq foreign key (url_stats_id) references url_stats;
alter table url_url_stats add constraint FK97wbkty0yufg3cyfenc3q1w0 foreign key (url_id) references url;
alter table url_stats add constraint FKqq0uktlox72vmsl5q67c305mf foreign key (url_id) references url;
create table url (id  bigserial not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
create table url_url_stats (url_id int8 not null, url_stats_id int8 not null, primary key (url_id, url_stats_id));
create table url_stats (id  bigserial not null, created_at timestamp, deleted_at timestamp, device_type varchar(255), updated_at timestamp, url_id int8 not null, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
alter table url_url_stats add constraint UK_l8de4ny4bkblamhklm7c5nhcv unique (url_stats_id);
alter table url_url_stats add constraint FKixdoppap48w5qd62i2x9oqsq foreign key (url_stats_id) references url_stats;
alter table url_url_stats add constraint FK97wbkty0yufg3cyfenc3q1w0 foreign key (url_id) references url;
alter table url_stats add constraint FKqq0uktlox72vmsl5q67c305mf foreign key (url_id) references url;
create table url (id  bigserial not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
create table url_url_stats (url_id int8 not null, url_stats_id int8 not null, primary key (url_id, url_stats_id));
create table url_stats (id  bigserial not null, created_at timestamp, deleted_at timestamp, device_type varchar(255), updated_at timestamp, url_id int8 not null, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
alter table url_url_stats add constraint UK_l8de4ny4bkblamhklm7c5nhcv unique (url_stats_id);
alter table url_url_stats add constraint FKixdoppap48w5qd62i2x9oqsq foreign key (url_stats_id) references url_stats;
alter table url_url_stats add constraint FK97wbkty0yufg3cyfenc3q1w0 foreign key (url_id) references url;
alter table url_stats add constraint FKqq0uktlox72vmsl5q67c305mf foreign key (url_id) references url;
