create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
create sequence hibernate_sequence start 1 increment 1;
create table url (id int8 not null, created_at timestamp, deleted_at timestamp, full_url varchar(255) not null, number_of_visits int4 not null, slug varchar(255) not null, updated_at timestamp, primary key (id));
alter table url add constraint UK_jpxnqjm5w5qj7h1q07l1if1t3 unique (slug);
